#!/usr/bin/env bash
# Backups for remote VPSs and local

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if ! [ $(uname -a | awk '{print $7;}') == "Cygwin" ]; then
    SUDOEX=sudo
else
    EXCYG='--exclude=/cygdrive/*'
fi

if [ $1 == 'whole' ]; then
    $SUDOEX tar -cvpzf $HOME/$(hostname)_$(date -I).tar.gz --exclude=$HOME/$(hostname)_$(date -I).tar.gz $EXCYG --one-file-system /
else
    tar -cvpzf $HOME/$(hostname)_home_$(date -I).tar.gz --exclude=$HOME/$(hostname)_home_$(date -I).tar.gz $HOME
fi
