#!/usr/bin/env bash
# Backups for remote VPSs and local

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if ! [ $(uname -a | awk '{print $7;}') == "Cygwin" ]; then
    SUDOX="sudo"

    if hash steam 2>/dev/null; then
        STEAMX="--exclude=$HOME/.steam/*"
    fi

    if hash wine 2>/dev/null; then
        STEAMX="$STEAMX --exclude=$HOME/.wine/*"
    fi
else
    CYGX="--exclude=/cygdrive/* --exclude=$HOME/.cygwin"
fi

HOMEX="--exclude=$HOME/$(hostname)_home_$(date +%Y-%m-%d).tar.gz --exclude=$HOME/.bashrc --exclude=$HOME/.profile --exclude=$HOME/.bash_profile --exclude=$HOME/.aliases --exclude=$HOME/.screenrc --exclude=$HOME/.bashrc --exclude=$HOME/.nanorc --exclude=$HOME/.tmux.conf --exclude=$HOME/.bash_history --exclude=$HOME/bin/* --exclude=$HOME/bin/ --exclude=$HOME/.cache/* --exclude=$HOME/.cache/ --exclude=$HOME/.ssh/* --exclude=$HOME/.ssh/ $CYGX $STEAMX"
WHOLEX="--exclude=/tmp/* --exclude=/proc/* --exclude=/tmp/ --exclude=/proc/ --exclude=$HOME/$(hostname)_$(date +%Y-%m-%d).tar.gz --exclude=/var/log/* --exclude=/var/log/ $HOMEX"

if [ "$1" == "whole" ]; then
    $SUDOEX tar -cvpzf $HOME/$(hostname)_$(date +%Y-%m-%d).tar.gz $WHOLEX --one-file-system /
else
    tar -cvpzf $HOME/$(hostname)_home_$(date +%Y-%m-%d).tar.gz $HOMEX $HOME
fi
