#!/usr/bin/env bash
# Backups for remote VPSs and local

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

WHOLEX="--exclude=/tmp --exclude=/proc --exclude=$HOME/$(hostname)_$(date -I).tar.gz --exclude=/var/log"
HOMEX="--exclude=$HOME/$(hostname)_home_$(date -I).tar.gz --exclude=$HOME/.bashrc --exclude=$HOME/.profile --exclude=$HOME/.bash_profile 
--exclude=$HOME/.aliases --exclude=$HOME/.screenrc --exclude=$HOME/.bashrc --exclude=$HOME/.nanorc --exclude=$HOME/updatedot 
--exclude=$HOME/.cache/* --exclude=$HOME/.ssh/* --exclude=$HOME/.ssh --exclude=$HOME/.cache"

if ! [ $(uname -a | awk '{print $7;}') == "Cygwin" ]; then
    SUDOEX=sudo
else
    EXCYG="--exclude=/cygdrive/* --exclude=$HOME/.cygwin"
fi

if [ "$1" == "whole" ]; then
    $SUDOEX tar -cvpzf $HOME/$(hostname)_$(date -I).tar.gz $WHOLEX $HOMEX $EXCYG --one-file-system /
else
    tar -cvpzf $HOME/$(hostname)_home_$(date -I).tar.gz $HOMEX $EXCYG $HOME
fi
