#!/usr/bin/env bash
# The script that pulls my dotfiles from Github

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if hash wget 2>/dev/null && [ -x "$( whereis wget | awk '{print $2;}' )" ] || [ -x "$( whereis wget | awk '{print $0;}' )" ]; then
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/dotfiles/master/.bashrc -O $HOME/.bashrc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/dotfiles/master/.aliases -O $HOME/.aliases
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/dotfiles/master/.screenrc -O $HOME/.screenrc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/dotfiles/master/.nanorc -O $HOME/.nanorc
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/dotfiles/master/.bash_profile -O $HOME/.bash_profile
    if ! [ -f "$HOME/.bashspec" ]; then wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/dotfiles/master/.bashspec -O $HOME/.bashspec; fi
    if hash tmux 2>/dev/null && [ -x "$( whereis tmux | awk '{print $2;}' )" ]; then wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/dotfiles/master/.tmux.conf -O $HOME/.tmux.conf; fi
    if [ $(uname -a | awk '{print $7;}') == "Cygwin" ]; then wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/dotfiles/master/.cygwin -O $HOME/.cygwin; fi
elif hash curl 2>/dev/null && [ -x "$( whereis curl | awk '{print $2;}' )" ] || [ -x "$( whereis curl | awk '{print $0;}' )" ]; then
    curl https://raw.githubusercontent.com/ianremsen/dotfiles/master/.bashrc > $HOME/.bashrc
    curl https://raw.githubusercontent.com/ianremsen/dotfiles/master/.aliases > $HOME/.aliases
    curl https://raw.githubusercontent.com/ianremsen/dotfiles/master/.screenrc > $HOME/.screenrc
    curl https://raw.githubusercontent.com/ianremsen/dotfiles/master/.nanorc > $HOME/.nanorc
    curl https://raw.githubusercontent.com/ianremsen/dotfiles/master/.bash_profile > $HOME/.bash_profile
    if ! [ -f "$HOME/.bashspec" ]; then curl https://raw.githubusercontent.com/ianremsen/dotfiles/master/.bashspec > $HOME/.bashspec; fi
    if hash tmux 2>/dev/null && [ -x "$( whereis tmux | awk '{print $2;}' )" ]; then curl https://raw.githubusercontent.com/ianremsen/dotfiles/master/.tmux.conf > $HOME/.tmux.conf; fi
    if [ $(uname -a | awk '{print $7;}') == "Cygwin" ]; then curl https://raw.githubusercontent.com/ianremsen/dotfiles/master/.cygwin > $HOME/.cygwin; fi
else
    echo "Neither wget nor curl are executable."
    exit 1
fi

source "$HOME/.bash_profile"
