#!/usr/bin/env bash
# The script that pulls my dotfiles from Github

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if ! [ -d "$HOME/bin" ]; then
    mkdir $HOME/bin
fi

if [ -n "$(command -v wget)" ] && [ -x "$( whereis wget | awk '{print $2;}' )" ] ||
                                  [ -x "$( whereis wget | awk '{print $0;}' )" ]; then
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/utils/master/bkup -O ~/bin/bkup
    if [ -n "$(command -v wget)" ]; then
        wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/utils/master/qdb -O ~/bin/qdb
    fi

    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/utils/master/updatedot -O ~/bin/updatedot
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/utils/master/updateutil -O ~/bin/updateutil
elif [ -n "$(command -v curl)" ] && [ -x "$( whereis curl | awk '{print $2;}' )" ] ||
                                    [ -x "$( whereis curl | awk '{print $0;}' )" ]; then
    curl https://raw.githubusercontent.com/ianremsen/utils/master/bkup > ~/bin/bkup
    if [ -n "$(command -v wget)" ]; then
        curl https://raw.githubusercontent.com/ianremsen/utils/master/qdb > ~/bin/qdb
    fi

    curl https://raw.githubusercontent.com/ianremsen/utils/master/updatedot > ~/bin/updatedot
    curl https://raw.githubusercontent.com/ianremsen/utils/master/updateutil > ~/bin/updateutil
else
    echo 'Neither wget nor curl are executable.'
    exit 1
fi

for file in `ls $HOME/bin`; do
    chmod 744 $HOME/bin/$file
done
