#!/usr/bin/env bash
# The script that pulls my utilities from Github

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if ! [ -d "$HOME/bin" ]; then
    mkdir $HOME/bin
fi

if hash wget 2>/dev/null && [ -x "$( whereis wget | awk '{print $2;}' )" ] ||
                            [ -x "$( whereis wget | awk '{print $0;}' )" ]; then
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/utils/master/bkup -O ~/bin/bkup
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/utils/master/dotup -O ~/bin/dotup
    wget --no-check-certificate https://raw.githubusercontent.com/ianremsen/utils/master/utilup -O ~/bin/utilup.new
elif hash curl 2>/dev/null && [ -x "$( whereis curl | awk '{print $2;}' )" ] ||
                              [ -x "$( whereis curl | awk '{print $0;}' )" ]; then
    curl https://raw.githubusercontent.com/ianremsen/utils/master/bkup > ~/bin/bkup
    curl https://raw.githubusercontent.com/ianremsen/utils/master/dotup > ~/bin/dotup
    curl https://raw.githubusercontent.com/ianremsen/utils/master/utilup > ~/bin/utilup.new
else
    echo "Neither wget nor curl are executable."
    exit 1
fi

for file in `ls $HOME/bin`; do
    chmod 744 $HOME/bin/$file
done

mv $HOME/bin/utilup.new $HOME/bin/utilup
